
services:
  dnf_mysql:
    image: dnf_mysql:1.0
    container_name: dnf_mysql
    restart: unless-stopped
    ports:
      - 3306:3306/tcp 
      - 5505:5505/tcp           
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root123    # 首次设置后再次修改需要进入容器修改密码，同时该密码也为game密码，root用户不可用于远程登录。
      SERVER_IP: dnf_server
      MYSQL_IP: dnf_mysql
      GATE_AES_KEY: a1b2c3d4e5f6789012345678901234567890abcdef0123456789abcdef012345 
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - dnf_net

  dnf_server:
    image: dnf_server:1.0
    container_name: dnf_server
    shm_size: 10g
    restart: unless-stopped
    ports:
      - "22:22"           # 服务器SSH端口
      - 7001:7001/tcp		  # df_channel_r
      - 7001:7001/udp		  # df_channel_r
      - 7200:7200/tcp		  # df_relay_r
      - 7200:7200/udp		  # df_relay_r
      - 10011:10011/tcp		# df_game_r[ch.11]
      - 11011:11011/udp		# df_game_r[ch.11]
      #- 10052:10052/tcp		# df_game_r[ch.52]PVP
      #- 11052:11052/udp		# df_game_r[ch.52]PVP
      - 2311:2311/udp		  # df_stun_r
      - 2312:2312/udp	  	# df_stun_r
      - 2313:2313/udp	  	# df_stun_r
    volumes:
      - ./server_data/root:/root
      - ./server_data/data:/data
      - ./server_data/log:/home/neople/game/log
      #- ./server_data/dp2:/dp2
    environment:
      TZ: Asia/Shanghai
      ROOT_PASSWORD: root123     # 服务器密码
      PUBLIC_IP: 10.0.0.8       # 本机IP或公网IP
      CLIENT_POOL_SIZE: 64   # 客户端池大小
      MYSQL_IP: dnf_mysql
    networks:
      - dnf_net

networks:
  dnf_net:
    driver: bridge